### ISSUE TITLE
can't find usage-info__monthlyInfo for some reason

### ISSUE THREAD

**Issue by billimek** [jantman/xfinity-usage#1]
Hey @jantman thanks for writing this.  I was also using the [WTFox version of this](https://github.com/WTFox/comcastUsage) as well and discovered that the old page doesn't seem to work anymore.  Then I found yours.  I'm doing [something to emit the metrics to inflixdb for grafana](https://github.com/billimek/comcastUsage-for-influxdb) and would like to make this work.

However, I'm having difficulty getting it to work.  It's complaining about not being able to find `usage-info__monthlyInfo` but I suspect the issue is earlier not being able to actually log in properly.  I get the same thing when I try a dummy password.  When I do this manually in chrome and inspect the page I do indeed see `usage-info__monthlyInfo`.

Are you able to successfully use this with the recent changes?  Is XFINITY_USER supposed to be just the username, or the username + `@comcast.com`?  I tried both to no avail.

```
root@3492ed8a72e5:/src# python xfinity_usage.py -vv
2017-06-22 18:20:01,066 [DEBUG xfinity_usage.py:130 - root.__init__() ] Getting browser instance...
2017-06-22 18:20:01,066 [DEBUG xfinity_usage.py:344 - root.get_browser() ] getting PhantomJS browser (local)
2017-06-22 18:20:02,149 [DEBUG xfinity_usage.py:360 - root.get_browser() ] returning browser
2017-06-22 18:20:02,149 [DEBUG xfinity_usage.py:137 - root.run() ] Getting page...
2017-06-22 18:20:02,149 [INFO xfinity_usage.py:315 - root.get() ] GET https://customer.xfinity.com/#/devices
2017-06-22 18:20:04,601 [DEBUG xfinity_usage.py:294 - root.do_screenshot() ] Screenshot: /src/1.png of: https://customer.xfinity.com/#/devices
2017-06-22 18:20:26,564 [DEBUG xfinity_usage.py:294 - root.do_screenshot() ] Screenshot: /src/2.png of: https://customer.xfinity.com/#/devices
2017-06-22 18:20:26,564 [INFO xfinity_usage.py:229 - root.get_usage_page() ] Sleeping 10s...


2017-06-22 18:20:37,408 [DEBUG xfinity_usage.py:294 - root.do_screenshot() ] Screenshot: /src/3.png of: https://customer.xfinity.com/#/devices
2017-06-22 18:20:37,410 [INFO xfinity_usage.py:234 - root.get_usage_page() ] <span class="polaris-greeting"> not in page source;login may have failed.
2017-06-22 18:20:38,233 [DEBUG xfinity_usage.py:294 - root.do_screenshot() ] Screenshot: /src/4.png of: https://customer.xfinity.com/#/devices
2017-06-22 18:20:39,091 [DEBUG xfinity_usage.py:294 - root.do_screenshot() ] Screenshot: /src/5.png of: https://customer.xfinity.com/#/devices
2017-06-22 18:20:40,241 [CRITICAL xfinity_usage.py:256 - root.get_usage() ] Unable to find monthly usage div on page
Traceback (most recent call last):
  File "xfinity_usage.py", line 251, in get_usage
    '//div[@class="usage-info__monthlyInfo"]'
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with xpath '//div[@class=\"usage-info__monthlyInfo\"]'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"125","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1$
52266","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"xpath\", \"sessionId\": \"68586e00-5777-11e7-bda0-53adf544cbba\", \"value\": \"//div[@class=\\\"usage-info__monthlyInfo\\\"]\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path
":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/68586e00-5777-11e7-bda0-53adf544cbba/element"}}
Screenshot: available via screen

2017-06-22 18:20:41,103 [ERROR xfinity_usage.py:303 - root.error_screenshot() ] Screenshot saved to: /src/webdriver_fail.png
2017-06-22 18:20:41,104 [ERROR xfinity_usage.py:304 - root.error_screenshot() ] Page title: XFINITY | My Account | EcoBill® Online Bill Pay
2017-06-22 18:20:41,109 [ERROR xfinity_usage.py:311 - root.error_screenshot() ] Page source saved to: /src/webdriver_fail.html
Traceback (most recent call last):
  File "xfinity_usage.py", line 522, in <module>
    res = script.run()
  File "xfinity_usage.py", line 140, in run
    res = self.get_usage()
  File "xfinity_usage.py", line 258, in get_usage
    raise RuntimeError('Unable to find monthly usage div.')
RuntimeError: Unable to find monthly usage div.
```

**Comment by jantman** [comment]
@billimek FYI the WTFox version is completely different, and not related to my code at all.

I'm actually sending the data to Graphite myself, with a wrapper script. I guess since a few people have asked about it, I should merge that as well. (my wrapper script just imports the class from this script, and then calls it and uses the return value of ``run()``).

This is currently working for me... the site broke yesterday morning, and the most recent changes are working for me as of now. What do the screenshots show?

I use the exact same username/password that I use in the browser - I believe I use my email, but either should work.

Given your report the day after I saw the changes, I'm a bit worried that maybe they're doing A/B testing or sending users to different layouts based on region or something... that would be a bit of a problem... can you see if checking out dce78d84daff9357a26c5d009c1937252403dc58 will fix it for you?

**Comment by billimek** [comment]
Ok, the issue turned out to be my runtime environment.  I was originally running in a docker image (`killercentury/python-phantomjs`) that has phantomjs v1.9.8 installed.  As I was digging into this and looking deeper, it appeared that the page was never even 'loading' properly in the 'browser'.

Switching to a newer image (`a1fred/docker-python-phantomjs`) with phantomjs v2.1.1 causes everything to magically work FYI.

**Comment by jantman** [comment]
@billimek Sorry for not clarifying that, I'm using 2.1.1 as well. I've updated the README and the docstring in the module as well.
