### ISSUE TITLE
Unable to run: can't kill an exited process

### ISSUE THREAD

**Issue by manderso7** [jantman/xfinity-usage#26]
## Bug Report

When reporting a bug, please provide all of the following information,
as well as any additional details that may be useful in reproducing or fixing
the issue:

### Version
```

xfinity-usage --version
xfinity-usage 3.0.1 <https://github.com/jantman/xfinity-usage>
```

### Installation Method

`pip install xfinity-usage`

### Supporting Software Versions

The output of ``python --version``, ``virtualenv --version`` and ``pip freeze | grep selenium`` in the environment
that xfinity-usage is running in, as well as your operating system type and version.
```
firefox --version
Mozilla Firefox 67.0
```
```
geckodriver --help
geckodriver 0.23.0
```
```
virtualenv --version
15.1.0
```
```
pip freeze | grep selenium
selenium==3.141.0
```

### Actual Output

```
xfinity-usage --b firefox -j -vv
2019-05-31 17:25:07,928 [DEBUG xfinity_usage.py:114 - root.__init__() ] Getting browser instance...
2019-05-31 17:25:07,928 [DEBUG xfinity_usage.py:120 - root.run() ] Getting page...
2019-05-31 17:25:07,928 [DEBUG xfinity_usage.py:391 - root.get_browser() ] getting Firefox browser (local)
2019-05-31 17:25:07,928 [DEBUG xfinity_usage.py:393 - root.get_browser() ] exporting DISPLAY=:0
2019-05-31 17:25:07,937 [DEBUG connectionpool.py:206 - urllib3.connectionpool._new_conn() ] Starting new HTTP connection (1): 127.0.0.1:42347
2019-05-31 17:25:08,046 [DEBUG connectionpool.py:396 - urllib3.connectionpool._make_request() ] http://127.0.0.1:42347 "POST /session HTTP/1.1" 500 110
Traceback (most recent call last):
  File "/opt/splunk/.local/bin/xfinity-usage", line 11, in <module>
    sys.exit(main())
  File "/opt/splunk/.local/lib/python2.7/site-packages/xfinity_usage/xfinity_usage.py", line 671, in main
    res = script.run()
  File "/opt/splunk/.local/lib/python2.7/site-packages/xfinity_usage/xfinity_usage.py", line 122, in run
    self.browser = self.get_browser()
  File "/opt/splunk/.local/lib/python2.7/site-packages/xfinity_usage/xfinity_usage.py", line 395, in get_browser
    browser = webdriver.Firefox()
  File "/opt/splunk/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/splunk/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/splunk/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/splunk/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/splunk/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

```

### Expected Output

Expect to see a json output of data usage from website.

### Testing Assistance

Sure. Thanks much.

**Comment by manderso7** [comment]
Am able to run on another machine with gui with 
```
➜ firefox --version                       
Mozilla Firefox 67.0
```
```
➜ geckodriver --version                                 
geckodriver 0.24.0 ( 2019-01-28)
```
```
➜ pip freeze | grep selenium
selenium==3.141.0
```
So I guess you can close this.
