### ISSUE TITLE
Possible Xfinity Server Issue

### ISSUE THREAD

**Issue by jantman** [jantman/xfinity-usage#5]
FYI, starting at 09:30 Eastern today, this script is failing for me on my account. The failures seem to be caused by some backend 500s on the site, and result in a "We are having some trouble connecting to My Account" error on the page. They appear to be happening intermittently for me in a normal browser as well, and so far, I don't think they're related to this script.

**Comment by jantman** [comment]
This was resolved at 13:00 Eastern. It's the longest outage I've seen so far, but the more automated tooling I have interacting with end user (non-API) websites, the less it surprises me when a site has a glitch for multiple hours...

**Comment by jantman** [comment]
This is back today, as of 12:00 Eastern exactly.

``webdriver_fail.png`` screenshot: 
![webdriver_fail](https://user-images.githubusercontent.com/273454/32468049-b8fbd090-c31a-11e7-867c-92614834c281.png)

Traceback:

```
2017-11-06 17:30:07,402 [DEBUG xfinity_usage.py:178 - root.do_login() ] Clicking "Remember Me"
2017-11-06 17:30:07,496 [DEBUG xfinity_usage.py:197 - root.do_login() ] Clicking Sign In button
2017-11-06 17:30:08,543 [WARNING xfinity_usage.py:236 - root.get_usage_page() ] Exception while logging in
Traceback (most recent call last):
  File "/home/jantman/GIT/xfinity-usage/xfinity_usage.py", line 233, in get_usage_page
    self.do_login()
  File "/home/jantman/GIT/xfinity-usage/xfinity_usage.py", line 199, in do_login
    btn.click()
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 60, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 370, in _execute
    return self._parent.execute(command, params)
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 415, in _request
    resp = opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
2017-11-06 17:30:08,544 [INFO xfinity_usage.py:237 - root.get_usage_page() ] Sleeping 5s...
Traceback (most recent call last):
  File "/home/jantman/GIT/privatepuppet/files/xfinity2graphite.py", line 145, in <module>
    res = u.run()
  File "/home/jantman/GIT/xfinity-usage/xfinity_usage.py", line 147, in run
    self.get_usage_page()
  File "/home/jantman/GIT/xfinity-usage/xfinity_usage.py", line 239, in get_usage_page
    self.wait_for_page_load()
  File "/home/jantman/GIT/xfinity-usage/xfinity_usage.py", line 384, in wait_for_page_load
    self.wait_for_ajax_load(timeout=timeout)
  File "/home/jantman/GIT/xfinity-usage/xfinity_usage.py", line 406, in wait_for_ajax_load
    self.doc_readystate_is_complete
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 63, in until
    value = method(self._driver)
  File "/home/jantman/GIT/xfinity-usage/xfinity_usage.py", line 373, in doc_readystate_is_complete
    result_str = self.browser.execute_script("return document.readyState")
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 401, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/jantman/venvs/foo/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 415, in _request
    resp = opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by jantman** [comment]
This is _not_ happening when I use the same URL, https://customer.xfinity.com/#/devices in a real browser (Google Chrome 62.0.3202.62 on Linux).

**Comment by jantman** [comment]
Nevermind. That's an error with phantomjs dieing on my end. I might look into adding configuration to choose between phantomjs and headless Chrome/chromedriver.
